# Generated by Django 4.0.4 on 2022-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputAnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_paunch', models.CharField(choices=[('1', 'Чёрный'), ('2', 'Рыжий, бурый'), ('3', 'Жёлтый')], default=1, max_length=50, verbose_name='Цвет брюшка')),
                ('color_thorax', models.CharField(choices=[('1', 'Чёрный'), ('2', 'Рыжий, бурый'), ('3', 'Жёлтый')], default=1, max_length=50, verbose_name='Цвет торакса')),
                ('place', models.CharField(choices=[('1', 'Хвойный лес'), ('2', 'Смешанный лес'), ('3', 'луг'), ('4', 'болото, мойма'), ('5', 'антропогенный ландшафт')], default=1, max_length=50, verbose_name='Место')),
                ('time', models.CharField(choices=[('1', 'II половина апреля'), ('2', 'I половина мая'), ('3', 'II половина мая'), ('4', 'I половина июня'), ('5', 'II половина июня'), ('6', 'I половина июля'), ('7', 'II половина июля'), ('8', 'I половина августа'), ('9', 'II половина августа'), ('10', 'I половина сентября'), ('11', 'II половина сентября')], default=1, max_length=50, verbose_name='Время')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Размер')),
            ],
        ),
        migrations.AddField(
            model_name='ant',
            name='ant_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
