# Generated by Django 4.0.4 on 2022-05-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inputant_ant_ant_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputant',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ant',
            name='ant_picture',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='inputant',
            name='color_paunch',
            field=models.CharField(choices=[('1', 'Чёрный'), ('2', 'Рыжий/бурый'), ('3', 'Жёлтый')], default=1, max_length=50, verbose_name='Цвет брюшка'),
        ),
        migrations.AlterField(
            model_name='inputant',
            name='color_thorax',
            field=models.CharField(choices=[('1', 'Чёрный'), ('2', 'Рыжий/бурый'), ('3', 'Жёлтый')], default=1, max_length=50, verbose_name='Цвет грудного отдела (торакса)'),
        ),
        migrations.AlterField(
            model_name='inputant',
            name='place',
            field=models.CharField(choices=[('1', 'Хвойный лес'), ('2', 'Смешанный лес'), ('3', 'Луг'), ('4', 'Болото, пойма'), ('5', 'Антропогенный ландшафт')], default=1, max_length=50, verbose_name='Место'),
        ),
    ]
